picture_board/picturalizer/urls.py
from django.urls import path
from . import views

app_name = 'picturalizer'

urlpatterns = [
    path('showall/', views.ShowAllView.as_view(), name='showall'),
    path('upload/', views.ImageUploadView.as_view(), name='imageupload'),
    path('<int:pk>/thread', views.thread, name='thread'),
]

picture_board/picture_board/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("picturalizer.urls"))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
# if settings == "DEBUG":
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

picture_board/picturalizer/models.py
from django.db import models
import PIL

class Image(models.Model):
    picture = models.FileField(upload_to='images/')
    title = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, default='名無し')

    def __str__(self):
        return self.title


class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE, related_name='comments')  # Imageモデルとの関連
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, default='名無し')

picture_board/picturalizer/forms.py
from django import forms
from .models import Image, Comment
from django.core.exceptions import ValidationError
from PIL import Image as PILImage

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['picture', 'author', 'title']

    def clean_picture(self):
        picture = self.cleaned_data.get('picture')
        if not picture:
            raise ValidationError('画像ファイルが必要です。')
        try:
            img = PILImage.open(picture)
            img.verify()  # 画像の整合性を検証（画像ファイルでない場合はエラーになる）
        except (IOError, SyntaxError):
            raise ValidationError('無効な画像ファイルです。画像ファイルをアップロードしてください。')

        return picture


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'author']
        labels = {
            'text':'新規コメント',
            'author':'送り主名'
        }

    # def clean(self):
    #     cleaned_data = super().clean()
    #     text = cleaned_data.get('text', '')
    #     author = cleaned_data.get('author', '')
    #     if not text == 'a':
    #         raise ValidationError('txtgatigau')
    #     if not author == 'a':
    #         raise ValidationError('authorgatigau')

picture_board/picturalizer/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import CreateView, ListView, DetailView
from django.urls import reverse_lazy

from . import models
from .models import Image, Comment
from .forms import ImageForm, CommentForm


def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('showall')
    else:
        form = ImageForm()

    context = {'form':form}
    return render(request, 'upload.html', context)

class ImageUploadView(CreateView):
    template_name = 'upload.html'
    form_class = ImageForm

    def get_success_url(self):
        return reverse_lazy('picturalizer:showall')
    


class CommentUploadView(CreateView):
    template_name = 'upload.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('showall')


class ShowAllView(ListView):
    model = Image
    template_name = 'show_all_thread.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        print(ctxt)
        return ctxt
    

def thread(request, pk):
    model = Image.objects.get(id=pk)
    form = CommentForm()

    if request.method == "POST":
        print("POSTーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー")
        form = CommentForm(request.POST)

        if form.is_valid():
            print("validation成功ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー")
            text = form.cleaned_data['text']
            author = form.cleaned_data['author']
            comment = Comment(
                image=model, 
                text=text, 
                author=author)
            comment.save()

    else:
        form = CommentForm()

    return render(request, "thread.html", {
        "model": model,
        "form": form})

class ThreadView(DetailView, generic.edit.ModelFormMixin):
    model = Image
    template_name = 'thread.html'
    fields = ()

    def get_context_data(self, **kwargs):
        ctxt = super().get_context_data(**kwargs)
        ctxt.update({
            'comment_form': CommentForm(**self.get_form_kwargs()),
        })
        print(ctxt)
        return ctxt
    
    def post(self, request, *args, **kwargs):
        if 'button_change_question_text' in request.POST:
            qform = CommentForm(**self.get_form_kwargs())

            if qform.is_valid():
                qform_query = qform.save(commit=False)
                qform_query.pk = Image.objects.filter(pk=self.kwargs['pk'])
                qform_query.save()
                return self.form_valid(qform)
            else:
                self.object = self.get_object()
                return self.form_invalid(qform)

picture_board/picturalizer/templates/picturalizer/show_all_thread.html
<h1>スレッド一覧</h1>
<h2><a href="{% url 'picturalizer:upload' %}">Upload more</a></h2>

{% for image in images %}
<a href="{% url 'picturalizer:thread' image.id %}"">
    <img src='{{ MEDIA_URL }}{{image.picture}}' width=200>
    <h2>{{ image.title }}</h2>
</a>


{% endfor %}

<!--ページネーション処理-->
{% if is_paginated %}
<div class="row justify-content-between align-items-center mb-4">
  <div class="col-lg">
    <nav aria-label="Bootstrap Pagination Example">
      <ul class="pagination mb-0">
        <!--前ページへのリンク-->
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          <span class="mr-1 d-none d-sm-inline-block">&larr;</span> Previous
          </a>
        </li>
        {% endif %}

        <!--ページ数表示-->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active">
              <a class="page-link" href="#">{{ page_num }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        <!--次ページへのリンク-->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Next<span class="ml-1 d-none d-sm-inline-block">&rarr;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
{% endif %}

picture_board/picturalizer/templates/picturalizer/upload.html
<h1>Please Upload</h1>

<form enctype="multipart/form-data" action="{% url 'picturalizer:upload' %}" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>

picture_board/templates/show_all_thread.html
<head>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<p><a href="{% url 'picturalizer:imageupload' %}">スレッド作成</a></p>
<h1>スレッド一覧</h1>

{% for object in object_list%}
<a href="{% url 'picturalizer:thread' object.id %}">
    <img src='{{ MEDIA_URL }}{{ object.picture }}' width=200>
    <h2>{{ object.title }}</h2>
</a>


{% endfor %}

<!--ページネーション処理-->
{% if is_paginated %}
<div class="row justify-content-between align-items-center mb-4">
  <div class="col-lg">
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center mb-0">
        
        <!--前ページへのリンク-->
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&larr;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <!--ページ数表示-->
        {% for page_num in page_obj.paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active" aria-current="page">
              <a class="page-link" href="#">{{ page_num }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        <!--次ページへのリンク-->
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&rarr;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</div>
{% endif %}

picture_board/templates/thread.html
<p><a href="{% url 'picturalizer:imageupload' %}">スレッド作成</a></p>
<img src='{{ MEDIA_URL }}{{model.picture}}' width=200>
<h1>{{ model.title }}</h1>

<h2 class="subtitle">コメント</h2>
{% for comment in model.comments.all %}
<article class="media">
    <div class="media-content">
        <div class="content">
            <p>
                <strong>
                    <p>{{ comment.text }}</p>
                    <small>{{ comment.created_at }}</small>
                </strong>
                <br>
            </p>
        </div>
    </div>
    <hr>
</article>
{% empty %}
<div class="notification">
    <p>コメントはまだありません。</p>
</div>
{% endfor %}


<form enctype="multipart/form-data" action="{% url 'picturalizer:thread' model.id %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Upload", name="button_change_question_text">
    </form>

picture_board/templates/upload.html
<h1>Please Upload</h1>

<form enctype="multipart/form-data" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Upload">
</form>